### ISSUE TITLE
Move Baking Bread.li into /blog

### ISSUE THREAD

**Issue by daviddarnes** [daviddarnes/bread.li#25]
Create a blog page with posts that are each of the Baking Bread.li videos, along with an explanation to them.

Not sure if the page should be /blog or if it should be the homepage until the site is fully formed.

**Comment by TimohStudios** [comment]
I say go. Load time will go insane if you keep everything on the homepage.

**Comment by daviddarnes** [comment]
Good point! However, nothing will be on the homepage! ha
