### ISSUE TITLE
Create a better templating structure

### ISSUE THREAD

**Issue by daviddarnes** [daviddarnes/bread.li#65]
Need to built out the template files, build some modular partials and possibly work in the neat grid structure. Basically all the front-end stuff, then review it in a screencast.

**Comment by daviddarnes** [comment]
#### layouts:
- default.html
- frontpage.html
- page.html
- post.html
- blog.html
- cms.html
- cmsdir.html

#### includes:
- favicons.html
- header.html
- footer.html
- feature.html
- postlist.html
- cmslist.html
- cmsdata.html

**Comment by TimohStudios** [comment]
Ah, good old Frontpage
